### ISSUE TITLE
jailbreak removes quoting incorrectly

### ISSUE THREAD

**Issue by luispedro** [peti/jailbreak-cabal#11]
With this input file:

```
name:                Test
version:             0.0.0
executable test
  main-is: Main.hs
  ghc-options: -rtsopts "-with-rtsopts=-A64m -n4m"
  build-depends:
    base
```

jailbreak produces this output file:

```
name: Test
version: 0.0.0
cabal-version: -any
license: UnspecifiedLicense

executable test
    main-is: Main.hs
    build-depends:
        base -any
    ghc-options: -rtsopts -with-rtsopts=-A64m -n4m
```

The quoting around "-with-rtsopts" was removing changing the meaning of the ghc-options line (in this case leading to an error).
