### ISSUE TITLE
jailbreaking is broken when using recent versions of Cabal

### ISSUE THREAD

**Issue by mpickering** [peti/jailbreak-cabal#13]
jailbreak-cabal strips all information about an executable when using ghcHEAD. Including dependency information, hs-src-dir information and so on.

Reproduction

```
nix-shell -p haskell.packages.ghcHEAD.jailbreak-cabal git
git clone https://github.com/jaspervdj/cabal-dependency-licenses.git
cd cabal-dependency-licenses
jailbreak-cabal cabal-dependency-licenses.cabal
cat cabal-dependency-licenses.cabal
```

All the information about the executable is stripped from the package.

```
name: cabal-dependency-licenses
version: 0.2.0.0
cabal-version: >=1.10
build-type: Simple
license: BSD3
license-file: LICENSE
copyright: 2014 Jasper Van der Jeugt
maintainer: Jasper Van der Jeugt <m@jaspervdj.be>
homepage: http://github.com/jaspervdj/cabal-dependency-licenses
bug-reports: http://github.com/jaspervdj/cabal-dependency-licenses/issues
synopsis: Compose a list of a project's transitive dependencies with their licenses
description:
    Compose a list of a project's transitive dependencies with their licenses
category: Distribution
author: Jasper Van der Jeugt <m@jaspervdj.be>
extra-source-files:
    CHANGELOG

source-repository head
    type: git
    location: https://github.com/jaspervdj/cabal-dependency-licenses

executable  cabal-dependency-licenses
    main-is: Main.hs
```

At nixpkgs commit 84f52d20f1e0ce8b49f569a100c4cc20c8a1b850
